language: go
go:
  - "1.9"
  - "1.11"
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -X POST -F 'repo=github.com/svenschoenung/mac' https://goreportcard.com/checks
